[build-system]
requires = [
    "setuptools >= 42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "discord >= 1.7.3",
    "parsimonious >= 0.8.1",
    "python-dotenv >= 0.19.0"
]