---
  - name: GodBot playbook
    hosts: GodBot
    become: yes
    become_user: ubuntu
    tasks:
      - name: clone / pull repo
        git:
          repo: https://github.com/Shirakawa42/GodBot.git
          dest: /home/ubuntu/GodBot_git
      - name: delete old .env and create new one
        shell:
          cmd: rm -rf .env & python3 -m venv .env
          chdir: /home/ubuntu/GodBot
      - name: install godbot package
        pip:
          name: /home/ubuntu/GodBot_git/dist/GodBot-0.0.2.tar.gz
          virtualenv: /home/ubuntu/GodBot/.env
      - name: kill old tmux session
        shell:
          cmd: tmux kill-session -t godbot
        ignore_errors: yes
      - name: run godbot script
        shell:
          cmd: tmux new-session -d -s "godbot" /home/ubuntu/GodBot/.env/bin/python3 /home/ubuntu/GodBot_git/start_bot.py
